spring.application.name=coa

server.port=9091
AEM_PAGE_USERNAME=quip-service-user
AEM_PAGE_PASSWORD=quipServiceUser
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring.cloud.config.enabled=false